// library for liquid crystal display 16 X 2 LCD 
// Code for Arduino UNO to Control LCD Screen and showing the Energy Generated by Piezo-Sensors

#include <LiquidCrystal.h>

// Initialize the LCD screen with the pin

LiquidCrystal lcd(12, 11, 5, 4, 3, 2);

// Variables to store footsteps and voltage

int footsteps = 0;
float totalVoltage = 0.0;
const int transducersPin = A0; //  the tap transducers is connected to analog pin A0

void setup() {

 // Setting up the LCD screen columns and rows for displaying the results taking the input from transducers
  lcd.begin(16, 2);
  pinMode(transducersPin, INPUT);
}

void loop() {
  // Read the analog value from the pressure transducers which detects the thrust from footsteps
 
 int transducersValue = analogRead(transducersPin);
 
 // Map the analog value to voltage based on thrust range

  float voltage = map(transducersValue, 0, 1023, 0, 4); // 0-4V range
  
// Update total voltage and footsteps as the footsteps increases and voltage changes            according to transducers value

  totalVoltage += voltage;
   
 footsteps++;
    voltage += voltagePerStep;
   
 // Display footsteps and voltage on the LCD screen on first and second rows 
  
  lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print("C = ");
    lcd.print(footsteps);

    lcd.setCursor(0, 1);
    lcd.print("V = ");
    lcd.print(voltage);
    delay(1000); // Delay for the results to display on screen
  }
}
